-- 코드를 입력하세요
SELECT YEAR(sales_date) 'YEAR', MONTH(sales_date)'MONTH', I.GENDER, COUNT(DISTINCT I.USER_ID) 'USERS'
FROM USER_INFO I JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, 3
ORDER BY 1,2,3;