-- 코드를 입력하세요
-- 16일 기준으로 생각해야 하기 때문에 START_DATE가 17이면 대여 가능이 나와야 한다. .
SELECT CAR_ID,
    CASE
        WHEN MAX('2022-10-16' BETWEEN START_DATE AND END_DATE)
        THEN '대여중'
        ELSE '대여 가능'
    END AS 'AVAILABILITY'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY 1
ORDER BY 1 DESC;

#SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY